### ISSUE TITLE
FIX for high cpu usage

### ISSUE THREAD

**Issue by houdang** [StreamWhatYouHear/SWYH#9] opened 2016-03-08 12:46 UTC
Hi their,

the program uses 100% cpu load and can be fixed easily.. but im not into C#.
Can someone have a look on this topic and include thos 4 lines of code?

http://www.streamwhatyouhear.com/forums/topic/fix-for-high-cpu-usage/

Thanks !!

**Comment by sebastienwarin** [comment] 2016-03-08 13:06
Hi houdang,
How I can reproduce this behavior ?
Thx

**Comment by houdang** [comment] 2016-03-09 08:04
I simply start the program and start sending.. that's all. cpu goes then high after some minutes.
The server is running linux with kodi. solution should be the one above in the link i posted.

Thanks ! And greeting from Nuremberg ;-)

**Comment by sebastienwarin** [comment] 2016-03-09 09:13
Hey,

I use SWYH since 15 minutes, with 5 connected clients. I try to disconnect & reconnect clients but the CPU usage is always about 5~10%, otherwise 0~2% (idle time with no connection).

![image](https://cloud.githubusercontent.com/assets/6674275/13629367/f925b08a-e5d8-11e5-9925-afaed70a2e74.png)

I used VLC as client for the test but if I use Kodi, I can reproduce the bug :) In fact, Kodi (and other client ???) create multiple connection to SWYH that raise the OnStreamDone event more times with the same SessionID. So in my code the first time I successfully removes the session but then I wait indefinitely to remove a session that no longer exists (without sleep = busy loop = high cpu usage) !

I don't use the code of slash from the forum to fix that, I just added a condition to remove the session if it exists ;)

Tell me if it's OK for you to close this issue.

**Closed** 2016-03-09 09:16 UTC
